
server:
  port: 8201
spring:
  application:
    name: spring-cloud-consumer-feign-hystrix

feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
